import './globals.css'
import { Inter } from 'next/font/google'
import styles from './page.module.css';
import { Navbar } from '@/components/Navbar';
import { ActiveLink } from '@/components/ActiveLink';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home - Carlos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      <body className={inter.className}>
      <main className={styles.main}>
        <Navbar/>
        {children}
      </main>
      </body>
    </html>
  )
}
